var meta=document.createElement('meta'),maincss=document.createElement('link'),pagecss=document.createElement('link'),sidecss=document.createElement('link'),mainfont=document.createElement('link');monofont=document.createElement('link'),precon=document.createElement('link');
meta.setAttribute('charset','UTF-8');
document.head.appendChild(meta);
meta=document.createElement('meta')
meta.httpEquiv='X-UA-Compatible';
meta.content='IE=edge';
document.head.appendChild(meta);
meta=document.createElement('meta')
meta.name='viewport';
meta.content='width=device-width, initial-scale=1.0';
document.head.appendChild(meta);
precon.rel='preconnect';
precon.href='https://fonts.googleapis.com';
document.head.appendChild(precon);
precon=document.createElement('link');
precon.rel='preconnect';
precon.href='https://fonts.gstatic.com';
precon.crossOrigin='crossorigin';
document.head.appendChild(precon);
maincss.rel=pagecss.rel=sidecss.rel=monofont.rel=mainfont.rel='stylesheet';
maincss.href='/style/main.css';
pagecss.href=`/style/${ptype}.css`;
if(ptype=='post'){
    sidecss.href=`/style/lyrics.css`;
}
mainfont.href='https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap';
monofont.href="https://fontlibrary.org//face/fantasque-sans-mono";
document.head.appendChild(maincss);
document.head.appendChild(mainfont);
document.head.appendChild(pagecss);
document.head.appendChild(sidecss);
document.head.appendChild(monofont);
